name: "Website"
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@master

      - uses: actions/checkout@master

      - name: Build
        run: make

      - uses: actions/upload-artifact@master
        with:
          name: page
          path: bin
          if-no-files-found: error
  
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: page
          path: .
      - name: Setup Pages
        uses: actions/configure-pages@master
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@master
        with:
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@master
